version: "3.9"

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
