version: "3.9"

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose React app on localhost:3000
    depends_on:
      - backend # Ensure backend runs first
    environment:
      - REACT_APP_API_URL=http://backend:5000/api # Backend service hostname for API
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose Flask API on localhost:5000
    stdin_open: true
    tty: true
